version: '3.7'

services:

    fast:
        image: ${PROJECT_NAME_IMAGE_NAME:-fast}
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - mongo
        stdin_open: true
        tty: true
        container_name: fast
        volumes:
            - ./:/app
        ports:
            - 80:80

    jaeger:
        image: jaegertracing/all-in-one:latest
        depends_on:
            - fast
        ports:
        - "6831:6831/udp"
        - "16686:16686"

    mongo:
        image: mongo:4.4-bionic
        container_name: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=mongoadmin
            - MONGO_INITDB_ROOT_PASSWORD=secret
        ports:
            - 27017:27017

    mongo_express:
        image: mongo-express:0.54.0
        container_name: mongo_express
        logging:
            driver: none
        depends_on:
            - mongo
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=mongoadmin
            - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
        ports:
            - 8081:8081    

networks:
    default:
        name: fast-environment-network